class_a <- c(76, 35, 47, 64, 95, 66, 89, 36, 84)
class_b <- c(51, 56, 84, 60, 59, 70, 63, 66, 50)
mean_a <- mean(class_a)
median_a <- median(class_a)
range_a <- diff(range(class_a))
mean_b <- mean(class_b)
median_b <- median(class_b)
range_b <- diff(range(class_b))
cat("Class A:\n")
cat("Mean:", mean_a, "\n")
cat("Median:", median_a, "\n")
cat("Range:", range_a, "\n\n")
cat("Class B:\n")
cat("Mean:", mean_b, "\n")
cat("Median:", median_b, "\n")
cat("Range:", range_b, "\n\n")
par(mfrow = c(1, 2)) 
boxplot(class_a, main = "Boxplot for Class A", ylab = "Scores", col = "lightblue")
boxplot(class_b, main = "Boxplot for Class B", ylab = "Scores", col = "lightgreen")
